export const clientList = [
  "BPCE",
  "SOCIETE DES AUTOROUTES DU NORD ET DE L EST DE LA FRANCE (SANEF)",
  "Banque fédérative du crédit mutuel",
  "Svenska Handelsbanken AB",
  "BANCA NAZIONALE DEL LAVORO S.P.A.",
  "Swedish Covered Bond Corp.The",
  "Statkraft AS",
  "Compagnie de Saint-Gobain S.A.",
  "Compass Group Fin. Netherl. BV",
  "Nordic Investment Bank",
  "Nykredit Bank A/S",
  "Raiffeisen-Landesbank Tirol AG",
  "HYPO TIROL BANK AG",
  "Raiffeisen Landesbank Vorarlberg mit Revisionsverband eGen",
  "Oberbank AG",
  "Raiffeisen Bank International AG",
  "HYPO NOE Landesbank für Niederösterreich und Wien AG",
  "UniCredit Bank Austria AG",
  "Erdöl-Lagergesellschaft m.b.H.",
  "Raiffeisenlandesbank Oberösterreich AG",
  "Raiffeisen-Landesbank Steiermark AG",
  "Raiffeisenverband Salzburg eGen",
  "Bausparkasse Wüstenrot AG",
  "RAIFFEISENLANDESBANK NIEDERÖSTERREICH-WIEN AG",
  "Slovenská sporiteľňa a.s.",
  "Erste Group Bank AG",
  "European Investment Bank",
  "Realkredit Danmark A/S",
  "E.ON SE",
  "FCC Serv.Medio Ambiente Hld.SA",
  "OP-Asuntoluottopankki Oyj",
  "Ferrovial S.A.",
  "Banco Santander S.A.",
  "Caisse Francaise d.Financ.Loc.",
  "BASF SE",
  "Unipol Gruppo S.p.A.",
  "Volkswagen Intl Finance N.V.",
  "EDP Finance B.V.",
  "Shell International Finance BV",
  "Nederlandse Waterschapsbank N.V.",
  "Norddeutsche Landesbank -Girozentrale-",
  "Bankinter S.A.",
  "Landesbank Baden-Württemberg",
  "BRED - Banque populaire",
  "Brandenburg Land",
  "JYSKE BANK A/S",
  "KLEPIERRE",
  "Société générale S.A.",
  "Nordea Mortgage Bank PLC",
  "VILLE DE PARIS",
  "REGION ILE DE FRANCE",
  "DECATHLON SA",
  "CREDIT LYONNAIS (LCL)",
  "DekaBank Deutsche Girozentrale",
  "Agence Centrale des Organismes de Sécurité Sociale (ACOSS)",
  "Natixis",
  "BNP Paribas",
  "Banca March S.A.",
  "Compagnie générale de location d'équipements C.G.L.",
  "PSA BANQUE FRANCE",
  "REGION HAUTS-DE-FRANCE",
  "REGION AUVERGNE-RHONE-ALPES",
  "DEPARTEMENT DE LA SEINE ET MARNE",
  "Banque Palatine",
  "BPCE SFH",
  "HSBC SFH (FRANCE)",
  "REGION DES PAYS DE LA LOIRE",
  "Caisse régionale de crédit agricole mutuel Sud Rhône-Alpes",
  "Crédit mutuel Arkéa",
  "Bpifrance",
  "Intesa Sanpaolo S.p.A.",
  "Crédit Agricole S.A.",
  "REGIE AUTONOME DES TRANSPORTS PARISIENS (RATP)",
  "Central government: Italian Republic",
  "Land Niederösterreich",
  "Ceske drahy a.s.",
  "Kon. KPN N.V.",
  "Santander Consumer Finance SA",
  "Asti Finance S.r.l.",
  "Central Bk of Sav.Bks Fin.PLC",
  "SELP Finance S.a.r.l.",
  "Svenska Handelsbanken AB [publ]",
  "Instituto de Credito Oficial",
  "International Bank for Reconstruction and Development",
  "Arkéa Home Loans SFH S.A.",
  "DEUTSCHSPRACHIGE GEMEINSCHAFT BELGIENS",
  "ALD",
  "ArcelorMittal S.A.",
  "Axa banque",
  "ENGIE",
]